{% set name = "pytest-fail-slow" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b367a5bdfadb0a4d35d4ef1c220737aa46bc8d6035256171004c67f7f2f5235c

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pluggy >=1.1
    - pytest >=7.0

test:
  requires:
    - python {{ python_min }}
  source_files:
    - test
    - tox.ini
  imports:
    - pytest_fail_slow
  commands:
    - python -m pytest -vv test

about:
  home: https://github.com/jwodder/pytest-fail-slow
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fail tests that take too long to run
  description: |
    `pytest-fail-slow` is a pytest plugin for treating tests as failed if they
    took too long to run.  It adds markers for failing tests if they or their
    setup stages run for longer than a given duration, along with command-line
    options for applying the same cutoff to all tests.
  dev_url: https://github.com/jwodder/pytest-fail-slow

extra:
  recipe-maintainers:
    - jwodder
