{% set name = "pytest-fail-slow" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fbfc3de71e9376a33c128324ef5e4826d8a8ea262b71abbc614f213508f619bd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pluggy >=1.1
    - pytest >=7.0

test:
  source_files:
    - test
    - tox.ini
  imports:
    - pytest_fail_slow
  commands:
    - python -m pytest -vv test

about:
  home: https://github.com/jwodder/pytest-fail-slow
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fail tests that take too long to run
  description: |
    `pytest-fail-slow` is a pytest plugin for treating tests as failed if they
    took too long to run.  It adds markers for failing tests if they or their
    setup stages run for longer than a given duration, along with command-line
    options for applying the same cutoff to all tests.
  dev_url: https://github.com/jwodder/pytest-fail-slow

extra:
  recipe-maintainers:
    - jwodder
